import { defineConfig, devices } from "@playwright/test";

/* End-to-end tests run against the local Supabase stack, so `npm run db:start`
   has to be up. They cover the things unit tests can't: signing in, two devices
   watching one account, and losing the network mid-session. */

export default defineConfig({
  testDir: "./e2e",
  fullyParallel: false,
  workers: 1,
  timeout: 45_000,
  reporter: [["list"]],
  use: {
    baseURL: "http://localhost:5180",
    trace: "retain-on-failure",
  },
  projects: [
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
    { name: "phone", use: { ...devices["iPhone 13"] } },
  ],
  /* The built app, not the dev server: the service worker is what makes an
     offline reload work, and it is only generated by a real build. */
  webServer: {
    command: "npm run build && npx vite preview --port 5180 --strictPort",
    url: "http://localhost:5180",
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
